export default{

    'title': '** Dental Hub **',
    'token': window.localStorage.getItem("token"),
    'users': [],
    'profile':'',
    'successmessage':'',
    'errormessage':'',
    'message':'',
    'geography': [],
    'activities': [],
    'genderchart':'',
    'visualizations1':'',
    'user_obj':'',
    'adminusername':'',
    'wards_obj':[],
    'address_obj':'',
    'role_obj':[],
    'loginvisualization':'',
    'treatmentnargraph':'',
    'treatmenttable':'',
    'basic_table':'',
    'wardsettingsgraph':'',
    'wardtreatmentsgraph':'',
    "loginvisualization1":"",
    "warduserlinegraph":[],
    "wardstrategicdata_obj":[],
    "activities_obj":[],
}
